### ISSUE TITLE
RSS 订阅收集

### ISSUE THREAD

**Issue by barretlee** [barretlee/translation-plan#1]
先列一个提纲，抽空找下 RSS 源：

- 硬件相关的新闻
- 系统 / 软件相关的更新
- 安全相关的最新动态
- 人工智能、深度学习等领域热点新闻
- 数据可视化领域
- Serverless 相关内容 / Web IDE 相关动态信息
- IoT 相关资讯
- 区块链技术

先列这么多，大部分是平时感兴趣的领域。

**Comment by barretlee** [comment]
在 feedly 上订阅了不少 RSS，感觉量有点大，后续筛选好文是个麻烦事儿=。 =

**Comment by barretlee** [comment]
![image](https://user-images.githubusercontent.com/2698003/54142921-aa3baf00-4463-11e9-91e0-3f8617add832.png)

**Comment by ttttmr** [comment]
推荐一个安全相关的，Google Project Zero https://googleprojectzero.blogspot.com/

**Comment by inJs** [comment]
@barretlee 请问一下你截图中的 软件是？？

**Comment by linkenwild** [comment]
> @barretlee 请问一下你截图中的 软件是？？

这个貌似是reeder,待求证

**Comment by zeroone001** [comment]
@inJs  推荐reeder

**Comment by barretlee** [comment]
@inJs @linkenwild 平时用的 Reeder，截图是 https://feedly.com/
